name: Docker Image CI and CD to Docker Hub repo

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        cd StoreConsoleApp/StoreConsoleApp.UI/
        docker build --tag jzhuang3/storeconsoleapp --file Dockerfile ..

    - name: Push Docker image to DockerHub
      run: |
        docker login -u "jzhuang3" -p ${{ secrets.DOCKERHUB_PSW }} docker.io
        docker push jzhuang3/storeconsoleapp
      
